# drupdate -- config.yml
# =========================
# To use, uncomment the below line(s) you find necessary, and replace
# the given values with your own.
#--------------------------------------------------------------------

#contrib-location: /home/paranoid4ndr0id/contrib/
#git-username: paranoid4ndr0id
#modules-to-update: metatag, google_analytics
